### ISSUE TITLE
Linux Camera DeviceDriver 포팅

### ISSUE THREAD

**Issue by kbu1564** [IWillFindYou/SecurityBootManager#1]
WebCam 지원을 위해 Grub WebCam Module 을 직접 처음부터 개발하는 것은 불가능 하다고 판단
방향을 바꾸어 리눅스의 Camera 관련 Media Device Driver의 포팅 가능성에 초점을 둠

리눅스의 HAL 계층의 맵핑 구조와 방식을 파악하여 Grub 에서 리눅스의 Device Driver 구동방식을 연결하는 것을 중점으로 분석할 예정

리눅스의 Cam 관련 디바이스 드라이버 분석을 통해 Grub Module 형식으로 포팅 가능여부에 대한 분석 및 이슈 시작

**Comment by kbu1564** [comment]
## 리눅스 캠 드라이버 관련 소스

https://github.com/torvalds/linux/tree/master/drivers/media
https://github.com/torvalds/linux/tree/master/drivers/media/usb/uvc
v4l 라이브러리를 이용
uvc(usb video class) device driver

## 리눅스 Camera의 HAL 조사

HAL 계층은 각 디바이스드라이버 별로 별도로 존재하되 이를 맵핑시켜주는 부분이 존재함.

따라서 아래의 부분에 대한 자료조사가 필요하다 느낌
1. 이 맵핑시켜주는 부분에 대한 자료
2. Camera 에서 사용되는 칩셋의 종류
3. 해당 칩셋에 대한 리눅스 HAL 계층의 소스 or Binary 파일

**Comment by kbu1564** [comment]
분석이 완성될때 까지 지속적으로 본 이슈를 수정

## Linux WebCam 분석글

linux의 경우 UVC Device Driver 를 통해 USB로 들어오는 Camera 를 인식하여 v4l api를 이용하여
구동시키는 방식으로 이루어져 있는것으로 보임

MacBook air, pro, ios, ... 의 경우 노트북 전방 웹캠을 **isight camera** 제품을 사용중

https://github.com/torvalds/linux/tree/master/drivers/media/usb/gspca
webcam device sensor 별 초기화 및 칩셋 구동 소스 코드

https://github.com/torvalds/linux/blob/master/drivers/media/usb/gspca/jpeg.h
JPEG Header & Huffman Table

### iSight Webcam

https://en.wikipedia.org/wiki/ISight
iSight Wiki

https://github.com/torvalds/linux/blob/master/drivers/media/usb/uvc/uvc_isight.c
linux usb video class for iSight decode

https://github.com/torvalds/linux/blob/master/drivers/usb/misc/isight_firmware.c
isight camera usb load & disconnect modules

iSight firmware 부분 소스를 조사하던중 리눅스 커널소스에 이러한 주석을 발견
**The isight firmware loading was reverse engineered by Johannes Berg.**
... 리버스 엔지니어링 해서 구현한 로드소스 였다는 것...
**따라서 isight_firmware.c 파일의 소스는 컴파일은 수행되어 실제 커널에 포함되지만 해당 로직을 호출하는 부분은 어디에도 존재하지 않으므로 단순 껍데기에 불과함..**

분석 하려는 카메라가 USB를 통한 것이 아닌 노트북 전방에 설치된 카메라를 구동할 예정이므로
- PIC에 할당된 것 일경우 IRQ 번호가 몇번인지를 확인 한 후 제어
- USB를 통한 제어일 경우 GRUB의 USB제어 함수를 이용하여 제어

둘중 어느것에 속한 것인지를 확인하기 위해 커널의 메시지를 확인하여 로그를 이용한 시점 분석

**Comment by kbu1564** [comment]
어렵다....ㅠㅠ

**Comment by kbu1564** [comment]
현재 다른 Machine의 노트북 일체형 Camera 정보
노트북에 설치되어져서 나오는 전방 캠의 경우 usb에 연결되어있으므로 grub 에서 usb 제어를 하면 될 것으로 보임

$lsusb
...
Bus 001 Device 004: ID 10f1:1a2a Importek Laptop Integrated Webcam
...

## Testing Machine Develop Environment

Host OS : MacbookAir 10.11
VM Machine Name : VirtualBox 5.0.10
VirtualBox Extension Pack : VirtualBox 5.0.10 - extension pack
Guest OS : Ubuntu 15.03

노트북에 일체화된 캠과 동일한 환경 구성을 위해 카메라를 가상머신에 셋팅하기 위해
설치된 VirtualBox와 동일한 버전의 확장팩을 설치하여야 함
major version 과 minor version 모두 일치해야 정상적으로 설치되며 둘중 하나라도 일치하지 않는경우
설치가 정상적으로 수행되지 않음

현재 Wireless Device는 Realtek rtl8189 칩셋으로 시도중

## HAL(Hardware Abstraction Layer)

hal -> udev -> systemd

**Comment by Rumo-Arf** [comment]
화장실 다녀오는 데 시간이 너무 오래 걸렸네요.
부트로더가 웹캠을 제어한다고 이해하고 있는데 맞나요?

**Comment by kbu1564** [comment]
@Rumo-Arf 넵 맞습니다~
죄송하지만 궁금하신 부분이나 조언해 주실 부분이시라면 별도의 이슈를 생성해 주시겠어요?
:)
