### ISSUE TITLE
grub -> syslinux 멀티부트로더 소스 분석 타겟 변경 관련

### ISSUE THREAD

**Issue by kbu1564** [IWillFindYou/SecurityBootManager#10]
현재 iPXE의 경우 Grub 에서 채택하여 사용중인 기본 멀티 부트로더이며, 해당 프로젝트는 이더넷 통신 만을 지원
gPXE의 경우 Fedora 에서 채택된 기본 멀티 부트로더인 SysLinux 에서 사용중이며 무선 통신관련 네트워크 TCP/IP 기반 wireless가 지원되므로 잠시 환경 구축 및 분석 타겟 방향 변경

관련 이슈 : #5 #6 #9
@tyburn117 @kbu1564

**Comment by tyburn117** [comment]
syslinux 다운 받는 곳 : https://www.kernel.org/pub/linux/utils/boot/syslinux/
Oct 14.

**Comment by tyburn117** [comment]
gpxe사이트(http://etherboot.org/wiki/wirelessboot)에 들어가면 gpxe의 wireless booting 을 지원하는 NIC는 구형 모델밖에 없다고 설명 되어 있다.(09' 이전 NIC)
하지만 ipxe사이트(http://ipxe.org/appnote/hardware_drivers) 에 들어가면 gpxe보다 상대적으로 최근의 NIC도 지원이 되어 있다.(wlan지원하는 NIC도 포함). 확실한 것은 아니지만 gpxe의 일부를 ipxe가 흡수하지 않았는지 확인을 해보아야 함.(아니면, etherboot.org 사이트가 업로드 된지 너무 오래됬거나)

**Comment by kbu1564** [comment]
@tyburn117 http://ipxe.org/cfg 여기 가보면 iPXE에서도 Wireless관련 활성화 네트워크 검색목록이 된다는데...?
한번 테스트 해보겠음

**Comment by tyburn117** [comment]
http://hmontoliu.blogspot.kr/2010/12/gpxe-boot-from-grub2.html

grub2에서 gpxe쓰는 법

**Comment by tyburn117** [comment]
@kbu1564 관련 setting이 있지만 자세한 정보가 없음. 판단하긴 이름

**Comment by kbu1564** [comment]
@tyburn117 소스분석 단위 작업을 수행할 것이라 상관없음

**Comment by kbu1564** [comment]
해당 이슈는 대안책을 발견 하였으므로 종료처리
