### ISSUE TITLE
camera 관련해서 이게 도움이 될 지 모르겠네요.

### ISSUE THREAD

**Issue by minarc** [IWillFindYou/SecurityBootManager#14]
http://askubuntu.com/questions/211702/camera-input-output-at-grub

리눅스 커널 디바이스 드라이버에 대해 조사를 하시더라구요.
커널 자체보다 이미 배포판으로 나와 있는 우분투 같은 것들을 조사 해 보셨으면 합니다.
아주 오래전에 아치 리눅스에서 비슷한 것을 본 기억이 있는데 도무지 찾질 못하겠군요.

**Comment by minarc** [comment]
가만 보니 뭔가 제가 잘 못 이해 한 것 같아 닫아야 겠습니다. -,.-;

그루브 자체로 카메라에 접근하시려던게 맞나요?

**Comment by kbu1564** [comment]
@Rumo-Arf 
말해주신 방법대로 저희는 현재 노트북 일체형 카메라를 커널 로드 전단계에서 구현하기 위해 작업중에 있습니다.

하지만 작업중인 위치가 커널조차 로드되기 전이다 보니 리눅스에 사용중인 디바이스 드라이버를 그대로 옮기는데 문제가 있었습니다.

조사해본 결과 내부적으로 노트북 일체형 카메라또한 USB에 물려져 있는 형태로 파악되어 Grub를 통한 USB제어를 하면 될 것으로 파악이 되나 해당 부분을 컨트롤해본적이 없어 이에대한 자료가 필요했었습니다.

그래서 이슈 올렸었죠.
관심가셔주셔서 정말 감사합니다 :)
