### ISSUE TITLE
중계서버 설계

### ISSUE THREAD

**Issue by yunheur** [IWillFindYou/SecurityBootManager#16]
현재 중계서버는 자식 클라이언트 쪽의 MAC 주소를 기준으로 하여 hash_map 으로 그룹화하여 관리하는 서버이다. 
- 부모클라이언트 : 스마트폰[안드로이드]
- 자식클라이언트 : PC

**중계서버 UML**
![image](https://cloud.githubusercontent.com/assets/10061834/12582981/ab43fabe-c483-11e5-867e-3b79497acac5.png)

수정 해야할 사항
- 디자인패턴
- OCP 적용

**Comment by kbu1564** [comment]
본 이슈에 대해 추후 다시 논의 하는 것으로 진행 이슈를 닫음
