### ISSUE TITLE
travis-ci 을 이용한 단위테스트 함수 dependency 설정 불가능 문제

### ISSUE THREAD

**Issue by kbu1564** [IWillFindYou/SecurityBootManager#28]
Suggested-by : @formfoxk #27 

현재 제작된 run-test.sh 쉘스크립트와 연동되어져 있는 travis-ci 의 구조적인 문제에 의해
외부에 정의되어있는 함수를 직접 끌어와서 사용하지 못하고

다시한번 복사 붙여넣기로 재 정의해야하는 중대 이슈가 존재함
해당 문제는 travis-ci 를 이용하려는 취지에 부합하지 않으므로 해당 이슈를 `중대이슈`로 설정하여

본 이슈를 다루기 위해 예전 브렌치를 다시 살릴 예정
또한 feature/travis-ci 브렌치는 이후 지속적으로 유지될 예정

**Comment by yunheur** [comment]
:+1:

**Comment by kbu1564** [comment]
**수정된 내용**
단위 테스트는 tests 폴더의 cpp or c 파일 하나당 하나씩 컴파일 작업이 수행됨
모든 단위 테스트 cpp or c 파일은 해당 파일의 이름과 동일한 dep 파일을 정의해야함
예)

```
tests/server_PacketParser_001.cpp
tests/server_PacketParser_001.dep
```

dep 파일의 작성시 두개의 변수값을 지원하며 각각 그 변수의 의미는 아래와 같음
**SOURCES** = Shell Script 배열 변수와 동일한 Syntax 방식으로 의존성에 해당하는 cpp,c 파일들의 경로를 입력하면됨 (워터마크 등의 문자 사용가능)
**HEADERS** = 의존성에 대한 C, CPP 파일이 참고하여 사용하는 헤더파일들의 Base 경로

상세 예제는 tests/server_PacketParser_001.\* 참고
