### ISSUE TITLE
iPXE VBE, VESA support 관련 (user interface)

### ISSUE THREAD

**Issue by tyburn117** [IWillFindYou/SecurityBootManager#31]
사용자 편의를 위하여 UI를 제작해야함.

**Comment by kbu1564** [comment]
iPXE 에서 현재 VESA, VGA 초기화가 지원되지 않으므로
해당 부분에 대한 디바이스 드라이버 제작은 현재 가능한 상태이므로 본이슈를 이용하여 
iPXE 에서 그래픽 드라이버를 제작하여 GUI 환경을 필요로 하는 부분에 쓰일 수 있도록 수정할 예정

**Comment by kbu1564** [comment]
### ipxe interrupt call & interrupt vector table setting
http://dox.ipxe.org/librm__mgmt_8c_source.html

void \_\_attribute\_\_ (( regparm ( 1 ) )) interrupt ( int intr );
REAL_CODE 매크로 상수는 16bits 기계어 명령어 코드를 생성하도록 정의되어져 있음

**Comment by kbu1564** [comment]
### ipxe interrupt call & interrupt vector table setting

http://dox.ipxe.org/librm__mgmt_8c_source.html

`void __attribute__ (( regparm ( 1 ) )) interrupt ( int intr );`
REAL_CODE 매크로 상수는 16bits 기계어 명령어 코드를 생성하도록 정의되어져 있음

https://github.com/IWillFindYou/SecurityBootManager/blob/8bfce94a31b4758f19b2e551d246ae0c43ccd268/core/ipxe/src/arch/x86/transitions/librm.S#L349
해당 부분에서 x86 CPU의 realmode -> protected mode로 switching  작업이 일어남

a20 gate를 이용하여 1MB 이상의 메모리활성화 루틴이 존재하므로 해당 파일의 코드 부분에서 그래픽 정보를 얻는 작업을 진행하면 좋을 것으로 보임

해야할 부분
1. 페이징 처리를 하는 루틴 부분을 찾아 비디오 카드에서 사용하는 물리 메모리 대역을 ReMapping 시켜야함
https://github.com/IWillFindYou/SecurityBootManager/blob/8bfce94a31b4758f19b2e551d246ae0c43ccd268/core/ipxe/src/arch/x86/transitions/librm.S#L1326
2. realmode interrupt 를 이용하여 Vga 설정값 얻기 arch/x86/include/vga.h 의 struct screening 참조
https://github.com/IWillFindYou/SecurityBootManager/blob/8bfce94a31b4758f19b2e551d246ae0c43ccd268/core/ipxe/src/arch/x86/interface/pcbios/vesafb.c

VESA Framebuffer 에 관련된 소스 발견
interrupt 10h ah = 4fh 를 이용한 vga 지원여부 및 그래픽 해상도 지원 목록 구하는 함수 vesafb_mode_list ()
https://github.com/IWillFindYou/SecurityBootManager/blob/8bfce94a31b4758f19b2e551d246ae0c43ccd268/core/ipxe/src/arch/x86/interface/pcbios/vesafb.c#L186

그래픽 라이브러리 작업 진행을 위한 VESA/VGA Driver 제작 관련 pull request
#44 support to change VESA/VBE mode in vesafb command for VESA/VBE
