### ISSUE TITLE
중계서버에서 패킷 암호화

### ISSUE THREAD

**Issue by yunheur** [IWillFindYou/SecurityBootManager#4]
중계서버로 작동중인 서버(리눅스)와 클라이언트(GRUB, Android) 간에 보안을 위한 암호화를 목적으로 한다

**Comment by yunheur** [comment]
**암호화 통신시 취약점/주의할점**

▶ [SSL암호화 통신에 취약점](http://www.huffingtonpost.kr/pakghun/story_b_6907466.html)

**Comment by yunheur** [comment]
**AES(Advanced Encryption Standard)**

AES암호화에 사용되는 단계들이다.

밑에 있는 것들이 알고리즘 이름들이다.
S-Box
ShiftRows
MixColumns
AddRoundKey

키 스케쥴다음, 가장 처음에 AddRoundKey로 CipherText를 암호화 시킨다. 그 다음, 위에 4 알고리즘을 CipherText에 적용한다. 비트크기에 따라 반복하는 수가 다르다. AES-128같은 경우는 9번, AES-192는 11번, 그리고 AES-256은 13번 반복한다.

4 알고리즘을 적용후, 마지막으로 S-Box, ShiftRows, 그리고 AddRoundKey를 적용한다.

▶ [나무위키](https://namu.wiki/w/%EA%B3%A0%EA%B8%89%20%EC%95%94%ED%98%B8%ED%99%94%20%ED%91%9C%EC%A4%80)

**Comment by yunheur** [comment]
**RSA 공개키 알고리즘**

RSA 알고리즘은 미국 MIT 의 Rivest, Shamir, Adleman 이 발표한 공개키 암호화 방식으로, 공개키 암호화의 개념을 수학 적으로 구체화 시킨 알고리즘

![image](https://cloud.githubusercontent.com/assets/10061834/12436256/ee59ffba-bf56-11e5-9d63-3859cd27ca18.png)

▶ [RSA 알고리즘](http://pracon.tistory.com/106)
▶ [C code to implement RSA Algorithm(Encryption and Decryption)](http://www.coders-hub.com/2013/04/c-code-to-encrypt-and-decrypt-message.html#.Vp7QCPmLRD8)

_자바, C언어(GRUB), C언어에서 메시지 교환시 암호화 및 복호화가 가능하도록 구현_

**Comment by yunheur** [comment]
**RSA 공개키 알고리즘**

C언어 테스트 결과
![image](https://cloud.githubusercontent.com/assets/10061834/12436394/45c36cc2-bf58-11e5-9378-b9d0af7ff5ff.png)

**Comment by kbu1564** [comment]
해당 부분은 중계서버와 Grub 추가 드라이버 간의 통신을 위한 Grub 용 RSA 알고리즘 인코드 디코드 함수가 필요
해당 부분에 대한 커밋을 위한 브렌치 생성후 커밋 바람

**Comment by formfoxk** [comment]
내일까지 완료 할 예정입니다

**Comment by yunheur** [comment]
별도의 Key Set(개인키, 공개키)를 생성해주는 프로그램을 구현
생성된 4개의 Key Set을 아래의 그림과 같이 분배

![image](https://cloud.githubusercontent.com/assets/10061834/12721231/17dedf28-c942-11e5-86b3-09f939445b63.png)

개인키와 공개키 생성 TEST
![image](https://cloud.githubusercontent.com/assets/10061834/12721283/67fe7126-c942-11e5-90d2-b9f68bad3eb3.png)
