### ISSUE TITLE
gPXE를 지원하는 하드웨어

### ISSUE THREAD

**Issue by tyburn117** [IWillFindYou/SecurityBootManager#5]
Realtek 8180/8185(rtl8180 driver; 8180는 802.11b, 8185는 802.11b/g)
802.11n을 지원하지 않는 모든 Atheros cards(ath5k driver)

**Comment by tyburn117** [comment]
qemu 가상화 네트워크 환경 구축법 찾을 것

**Comment by kbu1564** [comment]
#7 #9 두 이슈와 주제가 비슷함
해당 이슈는 종료 처리 하겠음
