### ISSUE TITLE
앞으로의 개선방향

### ISSUE THREAD

**Issue by tyburn117** [IWillFindYou/SecurityBootManager#52]
1. wpa지원 ==> 네트워크 드라이버 패치
2. 프로젝트 정체성 찾기
   2.1 프로젝트 이름 리뉴얼
   2.2 프로젝트 readme 수정 (영문도 지원)
   2.3 경량화 시도 시 시스템 목적 및 요구사항 수정, 설계 리모델링
3. 프로젝트 홍보 수단 강구
4. 경량화 시도 (grub 유무 고려, 시스템 목적 경량화)

홧팅

**Comment by tyburn117** [comment]
[제안들] 
5. 정보 수집 모듈화 ( 다른 개발자들이 참여하기 편하도록!, A 개발자는 키보드 이벤트를 수집하는 모듈을 제작, B개발자는 사운드 정보를 수집하는 모듈을 제작 .. !) 
6. 누구든 쉽게 다룰 수 있게 만들자! and 쉽게 원하는 정보 수집 모듈을 선택하여 입맛에 맞게 쓸 수 있도록 하자!(원하는 정보를 소스코드 수정 없이 가져올 수 있도록! ==> config파일을 통하여 원하는 수집할 정보를 선택할 수 있게, 그리고 필요한 환경 변수를 선택 할 수 있게..! 마치 makefile처럼)
7. 하나의 예제가 생각났는데 회사 컴퓨터에 캠을 달아 A컴퓨터의 사용자가 부팅 때마다 기록에 남겨진다.! (유선) 
 ==> A씨의 컴퓨터를 누군가 몰래 썼다면 로그를 통하여 알 수 있다. ==> 정보 유출 예방

Beyond Stage 까지 모두 힘내욧!

**Comment by Jungmo** [comment]
시연하실때 웹에서 로그 기록하실때 IP가 기록되어지던데, 시연 당시 NAT를 사용해서 사설 IP가 기록이 되는데, 이 부분은 해결하실 문제인가요?

**Comment by kbu1564** [comment]
@Jungmo 해당 부분은 망내부에서의 테스트에 의해 사설아이피로 기록이 되어졌으나, 외부와의 통신이 될 경우 올바르게 외부 아이피로 기록이 될 것입니다.

망내부에서의 통신은 사설아이피가 기록되어야 한다고 생각하여 로그기록을 시연당시와 같이 보여드리게 되었었습니다.

**Comment by tyburn117** [comment]
@Jungmo 
애매한 부분이 많은 저희 프로젝트에 관심 가져 주셔서 감사합니다.
지금 현재 프로젝트 방향을 좀 더 정확한 방향으로 돌리고 있습니다.
시연 시엔 사설 IP가 수집되는 것은 저희의 의도였습니다.
Beyond Stage 까지 많이 달라질 예정이니 많은 관심 부탁드립니다!
Thanks!!

**Comment by Jungmo** [comment]
답변 감사합니다~ 저한텐 어떤 프로젝트보다 제일 신기했습니다. ㅎㅎ..

**Comment by tyburn117** [comment]
@Jungmo 이건 이 이슈와 관련이 없지만.. 
ㅋㅋㅋㅋ 저번에 보니깐 머신러닝에 관심이 많으시던데
괜찮다면 나중에 제가 궁금한 내용들이 생기면 물어봐도 될까요??

**Comment by kbu1564** [comment]
@Jungmo
정말 감사합니다. 개인적으로 저에게는 지금 천냥과도 같은 말을 해주셨습니다. :)

**Comment by Jungmo** [comment]
@tyburn117 저도 건드리고만 있는 정도라 물어봐주시면 저도 공부해서 알려드릴게요  ㅋㅋ
@kbu1564 다같이 열심히 해봅시다 화이팅!
