### ISSUE TITLE
IEEE 802.11 qemu 환경 구축 방법

### ISSUE THREAD

**Issue by tyburn117** [IWillFindYou/SecurityBootManager#6]
http://etherboot.org/wiki/wirelessboot
를 참고하여 계속 추가하겠음.

**Comment by kbu1564** [comment]
QEMU도 있지만 조금 나중에 나온 KVM 도 있음
KVM 에 대한 조사도 필요 할 것으로 보임

http://www.iamroot.org/xe/Hypervisor_3_KVM/72349
KVM 분석자료
http://wiki.qemu.org/KVM
Qemu의 KVM관련 위키

**Comment by tyburn117** [comment]
Xen은 반가상화 시스템이기 때문에 커널 수정이 요구됨.

**Comment by kbu1564** [comment]
http://wiki.kanotype.net/ko/QEMU
QEMU 옵션 관련 설명 위키

**Comment by kbu1564** [comment]
실머신에서 빌드 및 테스트를 수행하는것으로 문제 해결
