### ISSUE TITLE
가상 Wifi환경 만드는 법[찾는 중]

### ISSUE THREAD

**Issue by tyburn117** [IWillFindYou/SecurityBootManager#9]
**필요 한 것** 
1. 가상 wifi환경 (wpa2, wpa, open)
2. wifi를 연결할 수 있는 가상 NIC

....
**문제점 1**
 wifi를 연결할려면 기본적으로 어떤 wifi신호와 연결할 것인지 선택해야 하기 때문에
연결할 기기의 SSID를 알아야 하며, 연결을 하고자 해도 권한을 가지고 있어야 하기 때문에 
그 권한을 풀기 위한 키를 가지고 있어야 한다.
자동으로 연결 할 수 있는 방법이 없을까?
그리고 만약 무료 와이파이가 근처에 없으면 wifi를 연결 할 수 있는 UI를 제공 해야 할 것이다.

**문제점 2**
또다른 문제점은 gPXE에서 제공하는 NIC가 있다는 것인데 이는 가상화로 만들기 힘들다.
그래도 혹시 모르니 일단 아무 wifi 환경을 만든 후 테스팅을 해보자.

**Comment by kbu1564** [comment]
**문제점1**
gPXE를 조금 더 조사해야 하지만 무선인터넷을 통한 통신이 지원된다는 것은 우리가 일반적으로 사용하는 방식과 비슷하게 이용이 가능하다는 소리이므로 1번의 경우 gPXE내부에서는 특정 칩셋에 한정적이지만 주변 와이파이 목록과 비밀번호가 걸려있을 경우 입력을 통한 연결등을 지원함

**문제점2**
실머신에서 테스트를 수행해 보고 일단 gPXE를 컴파일하여 설치하는것이 최우선으로 보임

**Comment by kbu1564** [comment]
이것 또한 #6 이슈와 동일선상에 존재하는 이슈라 판단됨
